FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
COPY . ./web-api
WORKDIR /web-api 
RUN dotnet publish -c Release -o output

FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS runtime
COPY --from=build /web-api/output /web-api
COPY appsettings.Production.json /web-api/appsettings.Production.json
WORKDIR /web-api
ENTRYPOINT ["dotnet", "/web-api/jncc-web-api.dll"]
