// <auto-generated />
using MapConfig.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace jnccwebapi.Migrations
{
    [DbContext(typeof(MapConfigContext))]
    [Migration("20190131133416_ModifyBaseLayerVisibility")]
    partial class ModifyBaseLayerVisibility
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MapConfig.Models.BaseLayer", b =>
                {
                    b.Property<long>("BaseLayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MetadataUrl");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.Property<string>("Url");

                    b.HasKey("BaseLayerId");

                    b.HasIndex("Name");

                    b.ToTable("BaseLayer");
                });

            modelBuilder.Entity("MapConfig.Models.Filter", b =>
                {
                    b.Property<long>("FilterId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Attribute");

                    b.Property<string>("Description");

                    b.Property<long>("LayerId");

                    b.Property<string>("LookupCategory");

                    b.Property<string>("MetadataUrl");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.HasKey("FilterId");

                    b.HasIndex("LayerId");

                    b.HasIndex("Name");

                    b.ToTable("Filter");
                });

            modelBuilder.Entity("MapConfig.Models.Layer", b =>
                {
                    b.Property<long>("LayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<long>("LayerGroupId");

                    b.Property<string>("MetadataUrl");

                    b.Property<string>("Name");

                    b.Property<float>("Opacity");

                    b.Property<long>("Order");

                    b.Property<string>("SubLayerGroup");

                    b.Property<string>("Type");

                    b.Property<string>("Url");

                    b.Property<bool>("Visible");

                    b.HasKey("LayerId");

                    b.HasIndex("LayerGroupId");

                    b.HasIndex("Name");

                    b.ToTable("Layer");
                });

            modelBuilder.Entity("MapConfig.Models.LayerGroup", b =>
                {
                    b.Property<long>("LayerGroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<long>("MapInstanceId");

                    b.Property<string>("Name");

                    b.HasKey("LayerGroupId");

                    b.HasIndex("MapInstanceId");

                    b.HasIndex("Name");

                    b.ToTable("LayerGroup");
                });

            modelBuilder.Entity("MapConfig.Models.Lookup", b =>
                {
                    b.Property<long>("LookupId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("LookupCategory");

                    b.Property<string>("Name");

                    b.HasKey("LookupId");

                    b.HasIndex("LookupCategory");

                    b.ToTable("Lookup");
                });

            modelBuilder.Entity("MapConfig.Models.MapInstance", b =>
                {
                    b.Property<long>("MapInstanceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaseLayerList");

                    b.Property<string>("Centre");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("VisibleBaseLayer");

                    b.Property<int>("Zoom");

                    b.HasKey("MapInstanceId");

                    b.HasIndex("Name");

                    b.ToTable("MapInstance");
                });

            modelBuilder.Entity("MapConfig.Models.Filter", b =>
                {
                    b.HasOne("MapConfig.Models.Layer", "Layer")
                        .WithMany("Filters")
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapConfig.Models.Layer", b =>
                {
                    b.HasOne("MapConfig.Models.LayerGroup", "LayerGroup")
                        .WithMany("Layers")
                        .HasForeignKey("LayerGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MapConfig.Models.LayerGroup", b =>
                {
                    b.HasOne("MapConfig.Models.MapInstance", "Map")
                        .WithMany("LayerGroups")
                        .HasForeignKey("MapInstanceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
